replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/shippingservice
  tag: v0.1.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 50051

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
